### ISSUE TITLE
Error in n >= lp : default method not implemented for type 'list'

### ISSUE THREAD

**Issue by luantranminh** [ovaexpert/ovarian-tumor-aggregation#1]
`pvals = matrix(p.adjust(pvals, method = "BH",
                        n=sum(!is.na(pvals)|is.nan(pvals))),
               nrow=nrow(pvals),
               dimnames=list(rownames(pvals), colnames(pvals)))`
this code at section 

> Training and evaluation of aggregation strategies

didn't work with error : 
Error in n >= lp : default method not implemented for type 'list'
![image](https://user-images.githubusercontent.com/25551568/40604819-8642a344-628a-11e8-88b9-1a303a4c7973.png)
Could you take a look, please ?

**Comment by bikol** [comment]
We are aware of this problem but we are not able to fix it in the near future.

One of the libraries changed interface in incompatible way. As a solution I recommend using exact R version (3.1.2) and library versions as described in packrat.lock file. Unfortunately Packrat sometimes is unable to fetch automatically appropriate version so you may need to do it manually -  we think that it is Packrat problem.

This step is one of the last in the procedure and is used only to adjust and compare p-values at the end of the raport. All results except p-vals are still available so you can comment out this part and corresponding part in .Rmd file.
